apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Build
on:
  push:
    branches:
      - "**"
jobs:
  build:
    steps:
      - name: Build
        kind: build
        uses: docker://maven:3.9.11-eclipse-temurin-25-noble
        shell: sh
        run: |
          mvn clean install
