apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Build
on:
  push:
    branches:
      - "**"
jobs:
  build:
    steps:
      - uses: https://github.com/cloudbees-io/checkout@v1
      - name: Build
        kind: build
        uses: docker://maven:3.9.11-eclipse-temurin-25-noble
        shell: sh
        run: |
          ls -la
          mvn clean install
